using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CharacterManager.UserMessages
{
    public static class WeaponTraitUserMessages
    {
        public static string Agonising = "Designed to inflict maximum pain, these weapons damage mind and morale as much as body. Every Wound inflicted by an Agonising weapon also inflicts 1 Shock.";
        public static string Arc = "The deadly electrical discharge of Arc weapons scrambles vehicle technology. Arc weapons gain +ED equal to their rating when you use them to attack a vehicle.";
        public static string Assault = "Optimised for firing whilst rushing righteously towards the enemy. You can fire an Assault weapon as part of a Sprint (p.180), but take a +2 DN penalty to the attack.";
        public static string Blast = "Explosive weapons can devastate multiple enemies with a single attack. When you fire or throw a Blast weapon, choose any point in range(including another character!), then make a DN 3 Ballistic Skill(A) Test.Apply Range effects as normal(p.184) unless you are using a thrown weapon like a grenade.If you fail the Test, the attack misses and Scatters(p,186). If you succeed, the explosion is centered on your target.";
        public static string Brutal = "Brutal weapons inflict appalling, traumatic wounds. When you roll Extra Damage Dice for a Brutal weapon: 1-2 inflicts 0 DMG, 3-4 inflicts 1 DMG, 5-6 inflicts 2 DMG.";
        public static string Force = "Psykers can channel the power of the Warp through the etheric circuit patterns and psycho-reactive materials of these weapons. If you have the PSYKER Keyword, you may add half of your (Wil) Rating to a Force weapon’s Damage Value. If you don’t have the PSYKER Keyword, a Force weapon’s damage is decreased by 2.";
        public static string Flamer = "Flamers spew a stream of burning chemical liquid. The flowing torrent of flame can be guided by the wielder of a Flamer to set multiple foes ablaze. Attacks made with a Flamer ignore cover. If you hit a target with a Flamer, blazing liquid fills the space between you and your target in a straight line. Anything in that line is also hit by the attack. You can Shift when you make a ranged attack Test with a Flamer to arc the stream of burning chemicals a number of metres equal to your Ballistic Skill Rating.Anything in this arc is hit by the attack.Whenever you hit multiple targets, roll damage once and apply that damage to all targets. Any target may attempt to reduce the damage using the rules for Dodging Area Effect Attacks on p.186. A weapon with the Flamer Trait is considered to have the Inflict(On Fire) Trait.";
        public static string Heavy = "Large and cumbersome weapons are difficult to wield accurately and effectively. You must have a Strength equal to the Heavy weapon’s rating to fire it normally.All attacks with a Heavy weapon are made with a +2 DN penalty if you do not meet the minimum Strength, and rolling a Complication as part of an attack knocks you Prone in addition to any other effects.Taking the Brace (p.189) Action or securing a Heavy weapon to something like a tripod negates the Heavy Trait.";
        public static string Inflict = "These weapons are designed to harm the target in cruel and unusual ways. Every Inflict weapon has a Condition that it imposes on the target if it deals a Wound. For example, if a weapon with Inflict (On Fire) deals a Wound to a target, the target is On Fire. If an Inflict weapon has a number, that number determines the number of any Test made to remove the Condition.For example, if a weapon with Inflict (Poisoned 4) Wounds a target, they are Poisoned, and the target would need to make a DN 4 Toughness Test to recover at the beginning of their next turn.";
        public static string Kustom = "You can replace this weapon Trait with any other Weapon Trait of your choice when you acquire a weapon with this Trait. If the Trait you select has a Rating (X), roll 1d3 to determine the Rating.";
        public static string Melta = "The sub-atomic bursts that spew from these weapons melt flesh and reduce armour to slag. When you roll Extra Damage Dice for a Melta weapon fired at Short Range: 1-2 0 DMG, 3-4 1 DMG, 5-6 2 DMG. Firing at short range against a vehicle or fortification: results of 1-3 1 DMG, 4-6 2 DMG.";
        public static string Parry = "You can use these weapons to deflect blows. You gain +1 Defence against melee attacks while wielding a Parry weapon.";
        public static string Pistol = "Built light to be drawn quickly and used in close quarters. Pistols can be fired while Engaged(p.184).";
        public static string Rad = "The dangerous radioactive materials fired by these weapons irrevocably damage flesh. When you roll Extra Damage Dice for a Rad weapon, you add the Rating to the results of the dice.";
        public static string RapidFire = "These weapons are capable of quickly unleashing a hail of death at close range. If you hit with a Rapid Fire weapon at Short Range, you gain Extra Damage Dice equal to the weapon’s Rapid Fire rating.";
        public static string Reliable = "A rugged and easily maintained weapon. You can ignore the first Complication related to this weapon per scene. Tests made to repair or maintain Reliable weapons are made with +1 bonus die.";
        public static string Rending = "These powerful weapons punch through armour. When you Shift an Exalted Icon as part of an attack with a Rending weapon, the weapon’s AP improves by the Rending rating for that attack.";
        public static string Silent = "These stealthy weapons are designed to deal damage as quietly as possible. When a weapon with this Trait is used as part of an attack, your Stealth Score is only reduced by 2.";
        public static string Sniper = "Weapons optimised for high accuracy over long range. When you Aim with a Sniper weapon you gain an additional + 1 bonus die to the attack, and gain +ED equal to the weapon’s Sniper rating.";
        public static string Spread = "These wide-bore weapons wreak havoc on closely packed combatants. When fired at Short Range, a Spread weapon can hit any number of targets as long as they are all within 3 metres of one another.When you fire a Spread Weapon at a Mob you gain +3 bonus dice.";
        public static string Supercharge = "The super-heated matter plasma weapons fire can be overcharged with undeniably deadly results for the target and, occasionally, the wielder. You can choose to fire a weapon with this Trait in Supercharge mode. If you roll a Complication, you take 1d6 Mortal Wounds. If you hit, the weapon deals an additional +3 ED.";
        public static string Unwieldy = "Whether unbalanced or too large, some weapons are harder to use. Attacks made with Unwieldy weapons have their DN increased by an amount equal to their Unwieldy rating.";
        public static string Waaagh = "Ork weapons defy understanding; they break the laws of mechanics and physics, but a Greenskin’s beliefs make them all the more deadly. If you are an Ork, you gain +1 bonus die to attacks with a WAAAGH! weapon.If you are also Wounded(p.193), you deal an extra +1 ED.";
        public static string Warp = "Powered by psychic energy, xenos technology, or the raw force of Chaos, few can face these ungodly weapons and emerge unharmed. A Warp Weapon has a Damage value equal to the target’s Total Resilience –4, unless the weapon’s listed Damage is higher.";
    }
}
